//! Autogenerated weights for pallet_staking
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `substrate-node`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_staking.
pub trait WeightInfo {
    fn stake() -> Weight;
    fn unstake() -> Weight;
    fn claim_rewards() -> Weight;
    fn set_reward_rate() -> Weight;
    fn fund_reward_pool() -> Weight;
}

/// Weights for pallet_staking using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Staking Stakers (r:1 w:1)
    /// Proof: Staking Stakers (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    /// Storage: Staking TotalStaked (r:1 w:1)
    /// Proof: Staking TotalStaked (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn stake() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3593`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 3593)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    
    /// Storage: Staking Stakers (r:1 w:1)
    /// Proof: Staking Stakers (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    /// Storage: Staking TotalStaked (r:1 w:1)
    /// Proof: Staking TotalStaked (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn unstake() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `178`
        //  Estimated: `3593`
        // Minimum execution time: 22_000_000 picoseconds.
        Weight::from_parts(23_000_000, 3593)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    
    /// Storage: Staking Stakers (r:1 w:1)
    /// Proof: Staking Stakers (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    fn claim_rewards() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `178`
        //  Estimated: `3593`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 3593)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    
    /// Storage: Staking RewardRate (r:0 w:1)
    /// Proof: Staking RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn set_reward_rate() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_000_000 picoseconds.
        Weight::from_parts(9_000_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    
    /// Storage: Staking RewardPool (r:1 w:1)
    /// Proof: Staking RewardPool (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn fund_reward_pool() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `1501`
        // Minimum execution time: 18_000_000 picoseconds.
        Weight::from_parts(19_000_000, 1501)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    /// Storage: Staking Stakers (r:1 w:1)
    /// Proof: Staking Stakers (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    /// Storage: Staking TotalStaked (r:1 w:1)
    /// Proof: Staking TotalStaked (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn stake() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3593`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 3593)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    
    /// Storage: Staking Stakers (r:1 w:1)
    /// Proof: Staking Stakers (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    /// Storage: Staking TotalStaked (r:1 w:1)
    /// Proof: Staking TotalStaked (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn unstake() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `178`
        //  Estimated: `3593`
        // Minimum execution time: 22_000_000 picoseconds.
        Weight::from_parts(23_000_000, 3593)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    
    /// Storage: Staking Stakers (r:1 w:1)
    /// Proof: Staking Stakers (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    fn claim_rewards() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `178`
        //  Estimated: `3593`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 3593)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    
    /// Storage: Staking RewardRate (r:0 w:1)
    /// Proof: Staking RewardRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn set_reward_rate() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_000_000 picoseconds.
        Weight::from_parts(9_000_000, 0)
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    
    /// Storage: Staking RewardPool (r:1 w:1)
    /// Proof: Staking RewardPool (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn fund_reward_pool() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `1501`
        // Minimum execution time: 18_000_000 picoseconds.
        Weight::from_parts(19_000_000, 1501)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}