//! Autogenerated weights for pallet_bridge
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `substrate-node`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_bridge.
pub trait WeightInfo {
    fn initiate_deposit() -> Weight;
    fn confirm_deposit() -> Weight;
    fn initiate_withdrawal() -> Weight;
    fn confirm_withdrawal() -> Weight;
    fn add_validator() -> Weight;
    fn remove_validator() -> Weight;
    fn set_confirmation_threshold() -> Weight;
}

/// Weights for pallet_bridge using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Bridge PendingDeposits (r:0 w:1)
    /// Storage: Bridge NextDepositId (r:1 w:1)
    /// Proof: Bridge PendingDeposits (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn initiate_deposit() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 0)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    
    /// Storage: Bridge PendingDeposits (r:1 w:1)
    /// Storage: Bridge BridgeValidators (r:1 w:0)
    /// Storage: Bridge ConfirmationThreshold (r:1 w:0)
    /// Storage: Bridge TotalBridgedIn (r:1 w:1)
    /// Proof: Bridge PendingDeposits (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn confirm_deposit() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `400`
        //  Estimated: `5465`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 5465)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    
    /// Storage: Bridge PendingWithdrawals (r:0 w:1)
    /// Storage: Bridge NextWithdrawalId (r:1 w:1)
    /// Storage: Bridge TotalBridgedOut (r:1 w:1)
    /// Proof: Bridge PendingWithdrawals (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn initiate_withdrawal() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `100`
        //  Estimated: `1585`
        // Minimum execution time: 30_000_000 picoseconds.
        Weight::from_parts(31_000_000, 1585)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    
    /// Storage: Bridge PendingWithdrawals (r:1 w:1)
    /// Storage: Bridge BridgeValidators (r:1 w:0)
    /// Storage: Bridge ConfirmationThreshold (r:1 w:0)
    /// Proof: Bridge PendingWithdrawals (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn confirm_withdrawal() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `400`
        //  Estimated: `5465`
        // Minimum execution time: 22_000_000 picoseconds.
        Weight::from_parts(23_000_000, 5465)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    
    /// Storage: Bridge BridgeValidators (r:1 w:1)
    /// Proof: Bridge BridgeValidators (max_values: Some(1), max_size: Some(1000), added: 1495, mode: MaxEncodedLen)
    fn add_validator() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `100`
        //  Estimated: `2485`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 2485)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    
    /// Storage: Bridge BridgeValidators (r:1 w:1)
    /// Proof: Bridge BridgeValidators (max_values: Some(1), max_size: Some(1000), added: 1495, mode: MaxEncodedLen)
    fn remove_validator() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `2485`
        // Minimum execution time: 18_000_000 picoseconds.
        Weight::from_parts(19_000_000, 2485)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    
    /// Storage: Bridge ConfirmationThreshold (r:0 w:1)
    /// Storage: Bridge BridgeValidators (r:1 w:0)
    /// Proof: Bridge ConfirmationThreshold (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    fn set_confirmation_threshold() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `100`
        //  Estimated: `1585`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(13_000_000, 1585)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    /// Storage: Bridge PendingDeposits (r:0 w:1)
    /// Storage: Bridge NextDepositId (r:1 w:1)
    /// Proof: Bridge PendingDeposits (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn initiate_deposit() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    
    /// Storage: Bridge PendingDeposits (r:1 w:1)
    /// Storage: Bridge BridgeValidators (r:1 w:0)
    /// Storage: Bridge ConfirmationThreshold (r:1 w:0)
    /// Storage: Bridge TotalBridgedIn (r:1 w:1)
    /// Proof: Bridge PendingDeposits (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn confirm_deposit() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `400`
        //  Estimated: `5465`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 5465)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    
    /// Storage: Bridge PendingWithdrawals (r:0 w:1)
    /// Storage: Bridge NextWithdrawalId (r:1 w:1)
    /// Storage: Bridge TotalBridgedOut (r:1 w:1)
    /// Proof: Bridge PendingWithdrawals (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn initiate_withdrawal() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `100`
        //  Estimated: `1585`
        // Minimum execution time: 30_000_000 picoseconds.
        Weight::from_parts(31_000_000, 1585)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    
    /// Storage: Bridge PendingWithdrawals (r:1 w:1)
    /// Storage: Bridge BridgeValidators (r:1 w:0)
    /// Storage: Bridge ConfirmationThreshold (r:1 w:0)
    /// Proof: Bridge PendingWithdrawals (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn confirm_withdrawal() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `400`
        //  Estimated: `5465`
        // Minimum execution time: 22_000_000 picoseconds.
        Weight::from_parts(23_000_000, 5465)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    
    /// Storage: Bridge BridgeValidators (r:1 w:1)
    /// Proof: Bridge BridgeValidators (max_values: Some(1), max_size: Some(1000), added: 1495, mode: MaxEncodedLen)
    fn add_validator() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `100`
        //  Estimated: `2485`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 2485)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    
    /// Storage: Bridge BridgeValidators (r:1 w:1)
    /// Proof: Bridge BridgeValidators (max_values: Some(1), max_size: Some(1000), added: 1495, mode: MaxEncodedLen)
    fn remove_validator() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `2485`
        // Minimum execution time: 18_000_000 picoseconds.
        Weight::from_parts(19_000_000, 2485)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    
    /// Storage: Bridge ConfirmationThreshold (r:0 w:1)
    /// Storage: Bridge BridgeValidators (r:1 w:0)
    /// Proof: Bridge ConfirmationThreshold (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    fn set_confirmation_threshold() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `100`
        //  Estimated: `1585`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(13_000_000, 1585)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}