//! Autogenerated weights for pallet_pdex
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `substrate-node`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_pdex.
pub trait WeightInfo {
    fn create_pool() -> Weight;
    fn add_liquidity() -> Weight;
    fn remove_liquidity() -> Weight;
    fn swap() -> Weight;
}

/// Weights for pallet_pdex using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Pdex PoolCount (r:1 w:1)
    /// Proof: Pdex PoolCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    /// Storage: Pdex AssetPairToPool (r:1 w:1)
    /// Proof: Pdex AssetPairToPool (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    /// Storage: Pdex Pools (r:0 w:1)
    /// Proof: Pdex Pools (max_values: None, max_size: Some(120), added: 2595, mode: MaxEncodedLen)
    fn create_pool() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3505`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 3505)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    
    /// Storage: Pdex Pools (r:1 w:1)
    /// Proof: Pdex Pools (max_values: None, max_size: Some(120), added: 2595, mode: MaxEncodedLen)
    /// Storage: Pdex UserLPTokens (r:1 w:1)
    /// Proof: Pdex UserLPTokens (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
    /// Storage: Assets Asset (r:2 w:2)
    /// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
    /// Storage: Assets Account (r:4 w:4)
    /// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
    fn add_liquidity() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `633`
        //  Estimated: `11426`
        // Minimum execution time: 85_000_000 picoseconds.
        Weight::from_parts(87_000_000, 11426)
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(8_u64))
    }
    
    /// Storage: Pdex Pools (r:1 w:1)
    /// Proof: Pdex Pools (max_values: None, max_size: Some(120), added: 2595, mode: MaxEncodedLen)
    /// Storage: Pdex UserLPTokens (r:1 w:1)
    /// Proof: Pdex UserLPTokens (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
    /// Storage: Assets Asset (r:2 w:2)
    /// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
    /// Storage: Assets Account (r:4 w:4)
    /// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
    fn remove_liquidity() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `633`
        //  Estimated: `11426`
        // Minimum execution time: 80_000_000 picoseconds.
        Weight::from_parts(82_000_000, 11426)
            .saturating_add(T::DbWeight::get().reads(8_u64))
            .saturating_add(T::DbWeight::get().writes(8_u64))
    }
    
    /// Storage: Pdex Pools (r:1 w:1)
    /// Proof: Pdex Pools (max_values: None, max_size: Some(120), added: 2595, mode: MaxEncodedLen)
    /// Storage: Assets Asset (r:2 w:0)
    /// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
    /// Storage: Assets Account (r:4 w:4)
    /// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
    fn swap() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `633`
        //  Estimated: `11426`
        // Minimum execution time: 70_000_000 picoseconds.
        Weight::from_parts(72_000_000, 11426)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    /// Storage: Pdex PoolCount (r:1 w:1)
    /// Proof: Pdex PoolCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    /// Storage: Pdex AssetPairToPool (r:1 w:1)
    /// Proof: Pdex AssetPairToPool (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    /// Storage: Pdex Pools (r:0 w:1)
    /// Proof: Pdex Pools (max_values: None, max_size: Some(120), added: 2595, mode: MaxEncodedLen)
    fn create_pool() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3505`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 3505)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    
    /// Storage: Pdex Pools (r:1 w:1)
    /// Proof: Pdex Pools (max_values: None, max_size: Some(120), added: 2595, mode: MaxEncodedLen)
    /// Storage: Pdex UserLPTokens (r:1 w:1)
    /// Proof: Pdex UserLPTokens (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
    /// Storage: Assets Asset (r:2 w:2)
    /// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
    /// Storage: Assets Account (r:4 w:4)
    /// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
    fn add_liquidity() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `633`
        //  Estimated: `11426`
        // Minimum execution time: 85_000_000 picoseconds.
        Weight::from_parts(87_000_000, 11426)
            .saturating_add(RocksDbWeight::get().reads(8_u64))
            .saturating_add(RocksDbWeight::get().writes(8_u64))
    }
    
    /// Storage: Pdex Pools (r:1 w:1)
    /// Proof: Pdex Pools (max_values: None, max_size: Some(120), added: 2595, mode: MaxEncodedLen)
    /// Storage: Pdex UserLPTokens (r:1 w:1)
    /// Proof: Pdex UserLPTokens (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
    /// Storage: Assets Asset (r:2 w:2)
    /// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
    /// Storage: Assets Account (r:4 w:4)
    /// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
    fn remove_liquidity() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `633`
        //  Estimated: `11426`
        // Minimum execution time: 80_000_000 picoseconds.
        Weight::from_parts(82_000_000, 11426)
            .saturating_add(RocksDbWeight::get().reads(8_u64))
            .saturating_add(RocksDbWeight::get().writes(8_u64))
    }
    
    /// Storage: Pdex Pools (r:1 w:1)
    /// Proof: Pdex Pools (max_values: None, max_size: Some(120), added: 2595, mode: MaxEncodedLen)
    /// Storage: Assets Asset (r:2 w:0)
    /// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
    /// Storage: Assets Account (r:4 w:4)
    /// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
    fn swap() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `633`
        //  Estimated: `11426`
        // Minimum execution time: 70_000_000 picoseconds.
        Weight::from_parts(72_000_000, 11426)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
}