//! Autogenerated weights for `pallet_ring_signatures`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0
//! DATE: 2025-08-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chameleon-dev`, CPU: `AMD EPYC 7R32`
//!
//! NOTE: These are placeholder weights. Run benchmarks for production values.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_ring_signatures.
pub trait WeightInfo {
    fn verify_ring_signature() -> Weight;
}

/// Weights for pallet_ring_signatures using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: RingSignatures UsedKeyImages (r:1 w:1)
    /// Storage: RingSignatures TotalSignaturesVerified (r:1 w:1)
    fn verify_ring_signature() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `3493`
        // Minimum execution time: 100_000 nanoseconds.
        Weight::from_parts(150_000_000, 3493)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

// For use in tests/mocks
impl WeightInfo for () {
    fn verify_ring_signature() -> Weight {
        Weight::from_parts(150_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}
