//! Autogenerated weights for pallet_emissions
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `substrate-node`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_emissions.
pub trait WeightInfo {
    fn set_lp_apy() -> Weight;
    fn claim_validator_rewards() -> Weight;
    fn claim_lp_rewards() -> Weight;
    fn update_emission_rate() -> Weight;
}

/// Weights for pallet_emissions using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Emissions PoolAPY (r:1 w:1)
    /// Proof: Emissions PoolAPY (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
    fn set_lp_apy() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `3501`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(13_000_000, 3501)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    
    /// Storage: Emissions ValidatorRewards (r:1 w:1)
    /// Proof: Emissions ValidatorRewards (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
    /// Storage: System Account (r:2 w:2)
    /// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    fn claim_validator_rewards() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `6196`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 6196)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    
    /// Storage: Emissions LPRewards (r:1 w:1)
    /// Proof: Emissions LPRewards (max_values: None, max_size: Some(96), added: 2571, mode: MaxEncodedLen)
    /// Storage: System Account (r:2 w:2)
    /// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    fn claim_lp_rewards() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `6196`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 6196)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    
    /// Storage: Emissions EmissionRate (r:1 w:1)
    /// Proof: Emissions EmissionRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn update_emission_rate() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `1501`
        // Minimum execution time: 10_000_000 picoseconds.
        Weight::from_parts(11_000_000, 1501)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    /// Storage: Emissions PoolAPY (r:1 w:1)
    /// Proof: Emissions PoolAPY (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
    fn set_lp_apy() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `3501`
        // Minimum execution time: 12_000_000 picoseconds.
        Weight::from_parts(13_000_000, 3501)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    
    /// Storage: Emissions ValidatorRewards (r:1 w:1)
    /// Proof: Emissions ValidatorRewards (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
    /// Storage: System Account (r:2 w:2)
    /// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    fn claim_validator_rewards() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `6196`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 6196)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    
    /// Storage: Emissions LPRewards (r:1 w:1)
    /// Proof: Emissions LPRewards (max_values: None, max_size: Some(96), added: 2571, mode: MaxEncodedLen)
    /// Storage: System Account (r:2 w:2)
    /// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    fn claim_lp_rewards() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `6196`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 6196)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    
    /// Storage: Emissions EmissionRate (r:1 w:1)
    /// Proof: Emissions EmissionRate (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn update_emission_rate() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `1501`
        // Minimum execution time: 10_000_000 picoseconds.
        Weight::from_parts(11_000_000, 1501)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}