//! # Stealth Addresses Pallet
//!
//! A FRAME pallet for stealth address generation and management, enabling
//! unlinkable payments in the Chameleon Network. Stealth addresses ensure
//! that each payment goes to a unique address, preventing blockchain
//! observers from linking payments to recipients.
//!
//! ## Overview
//!
//! This pallet provides:
//! - Registration of stealth meta-addresses (spend + view key pairs)
//! - Announcement of stealth payments via ephemeral public keys
//! - Scanning functionality for recipients to find their payments
//!
//! ## Key Concepts
//!
//! - **Stealth Meta-Address**: A pair of public keys (spend pubkey + view pubkey)
//!   that allows anyone to compute a one-time stealth address for the owner.
//! - **Ephemeral Key**: A one-time public key generated by the sender and
//!   published on-chain so the recipient can find and claim the payment.
//! - **Stealth Address**: A one-time address derived from the recipient's
//!   meta-address and the sender's ephemeral key.
//!
//! ## Protocol Flow
//!
//! 1. Recipient registers their stealth meta-address (spend_pubkey, view_pubkey)
//! 2. Sender generates ephemeral keypair (r, R = r*G)
//! 3. Sender computes stealth address: P = spend_pubkey + H(r * view_pubkey) * G
//! 4. Sender publishes ephemeral pubkey R via `announce_payment`
//! 5. Recipient scans ephemeral keys and derives private key for P
//!
//! ## EIP-5564 Compatibility
//!
//! This implementation follows the stealth address standard from EIP-5564,
//! adapted for the Substrate ecosystem.

#![cfg_attr(not(feature = "std"), no_std)]

pub use pallet::*;

#[cfg(test)]
mod mock;

#[cfg(test)]
mod tests;

#[cfg(feature = "runtime-benchmarks")]
mod benchmarking;

pub mod weights;
pub use weights::WeightInfo;

#[frame_support::pallet]
pub mod pallet {
    use super::*;
    use frame_support::pallet_prelude::*;
    use frame_system::pallet_prelude::*;
    use sp_runtime::traits::Saturating;
    use sp_std::vec::Vec;

    /// Stealth meta-address structure.
    #[derive(Clone, Encode, Decode, Eq, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen)]
    pub struct StealthMetaAddress {
        /// Public key for spending (controls the funds).
        pub spend_pubkey: [u8; 32],
        /// Public key for viewing (allows scanning without spending).
        pub view_pubkey: [u8; 32],
    }

    /// Ephemeral key announcement structure.
    #[derive(Clone, Encode, Decode, Eq, PartialEq, RuntimeDebug, TypeInfo, MaxEncodedLen)]
    #[scale_info(skip_type_params(T))]
    pub struct EphemeralKeyAnnouncement<T: Config> {
        /// The ephemeral public key.
        pub ephemeral_pubkey: [u8; 32],
        /// Block number when announced.
        pub block_number: BlockNumberFor<T>,
        /// Optional encrypted memo for the recipient.
        pub encrypted_memo: BoundedVec<u8, T::MaxMemoSize>,
    }

    /// The module configuration trait.
    #[pallet::config]
    pub trait Config: frame_system::Config {
        /// The overarching event type.
        type RuntimeEvent: From<Event<Self>> + IsType<<Self as frame_system::Config>::RuntimeEvent>;

        /// Maximum size of encrypted memo attached to ephemeral keys.
        #[pallet::constant]
        type MaxMemoSize: Get<u32>;

        /// Number of blocks to retain ephemeral keys (for scanning window).
        #[pallet::constant]
        type EphemeralKeyRetentionPeriod: Get<u32>;

        /// Maximum ephemeral keys per block (DoS protection).
        #[pallet::constant]
        type MaxEphemeralKeysPerBlock: Get<u32>;

        /// Weight information for extrinsics in this pallet.
        type WeightInfo: WeightInfo;
    }

    #[pallet::pallet]
    pub struct Pallet<T>(_);

    /// Registered stealth meta-addresses by account.
    #[pallet::storage]
    #[pallet::getter(fn stealth_meta_addresses)]
    pub type StealthMetaAddresses<T: Config> = StorageMap<
        _,
        Blake2_128Concat,
        T::AccountId,
        StealthMetaAddress,
        OptionQuery,
    >;

    /// Ephemeral keys announced per block for scanning.
    #[pallet::storage]
    #[pallet::getter(fn ephemeral_keys)]
    pub type EphemeralKeys<T: Config> = StorageMap<
        _,
        Twox64Concat,
        BlockNumberFor<T>,
        BoundedVec<EphemeralKeyAnnouncement<T>, T::MaxEphemeralKeysPerBlock>,
        ValueQuery,
    >;

    /// Total registered meta-addresses (for metrics).
    #[pallet::storage]
    #[pallet::getter(fn total_meta_addresses)]
    pub type TotalMetaAddresses<T: Config> = StorageValue<_, u64, ValueQuery>;

    /// Total ephemeral keys announced (for metrics).
    #[pallet::storage]
    #[pallet::getter(fn total_ephemeral_keys)]
    pub type TotalEphemeralKeys<T: Config> = StorageValue<_, u64, ValueQuery>;

    /// Events emitted by this pallet.
    #[pallet::event]
    #[pallet::generate_deposit(pub(super) fn deposit_event)]
    pub enum Event<T: Config> {
        /// A stealth meta-address was registered.
        MetaAddressRegistered {
            account: T::AccountId,
            spend_pubkey: [u8; 32],
            view_pubkey: [u8; 32],
        },
        /// A stealth meta-address was updated.
        MetaAddressUpdated {
            account: T::AccountId,
            spend_pubkey: [u8; 32],
            view_pubkey: [u8; 32],
        },
        /// A stealth payment was announced (ephemeral key published).
        StealthPaymentAnnounced {
            ephemeral_pubkey: [u8; 32],
            block: BlockNumberFor<T>,
            has_memo: bool,
        },
        /// Old ephemeral keys were pruned.
        EphemeralKeysPruned {
            block: BlockNumberFor<T>,
            count: u32,
        },
    }

    /// Errors that can occur in this pallet.
    #[pallet::error]
    pub enum Error<T> {
        /// Meta-address already registered for this account.
        AlreadyRegistered,
        /// No meta-address registered for this account.
        NotRegistered,
        /// Invalid public key format (not on curve or zero).
        InvalidPublicKey,
        /// Ephemeral keys limit reached for this block.
        TooManyEphemeralKeys,
        /// Memo exceeds maximum size.
        MemoTooLarge,
        /// The spend and view pubkeys must be different.
        IdenticalKeys,
    }

    /// Hooks for block lifecycle.
    #[pallet::hooks]
    impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
        /// On finalize, prune old ephemeral keys outside the retention window.
        fn on_finalize(block_number: BlockNumberFor<T>) {
            let retention_period = T::EphemeralKeyRetentionPeriod::get();
            if let Some(prune_block) = block_number.checked_sub(&retention_period.into()) {
                let keys = EphemeralKeys::<T>::take(prune_block);
                if !keys.is_empty() {
                    Self::deposit_event(Event::EphemeralKeysPruned {
                        block: prune_block,
                        count: keys.len() as u32,
                    });
                }
            }
        }
    }

    /// Dispatchable functions (extrinsics).
    #[pallet::call]
    impl<T: Config> Pallet<T> {
        /// Register a stealth meta-address for receiving private payments.
        ///
        /// ## Arguments
        /// - `origin`: The transaction origin (must be signed).
        /// - `spend_pubkey`: Public key for spending funds.
        /// - `view_pubkey`: Public key for scanning payments.
        ///
        /// ## Errors
        /// - `AlreadyRegistered`: Meta-address already exists for this account.
        /// - `InvalidPublicKey`: One or both keys are invalid.
        /// - `IdenticalKeys`: Spend and view keys must be different.
        #[pallet::call_index(0)]
        #[pallet::weight(T::WeightInfo::register_meta_address())]
        pub fn register_meta_address(
            origin: OriginFor<T>,
            spend_pubkey: [u8; 32],
            view_pubkey: [u8; 32],
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;

            // Check not already registered
            ensure!(
                !StealthMetaAddresses::<T>::contains_key(&who),
                Error::<T>::AlreadyRegistered
            );

            // Validate keys are not zero
            ensure!(spend_pubkey != [0u8; 32], Error::<T>::InvalidPublicKey);
            ensure!(view_pubkey != [0u8; 32], Error::<T>::InvalidPublicKey);

            // Spend and view keys should be different for security
            ensure!(spend_pubkey != view_pubkey, Error::<T>::IdenticalKeys);

            // Store the meta-address
            let meta_address = StealthMetaAddress {
                spend_pubkey,
                view_pubkey,
            };
            StealthMetaAddresses::<T>::insert(&who, meta_address);

            // Update metrics
            TotalMetaAddresses::<T>::mutate(|count| *count = count.saturating_add(1));

            Self::deposit_event(Event::MetaAddressRegistered {
                account: who,
                spend_pubkey,
                view_pubkey,
            });

            Ok(())
        }

        /// Update an existing stealth meta-address.
        ///
        /// ## Arguments
        /// - `origin`: The transaction origin (must be signed).
        /// - `spend_pubkey`: New public key for spending funds.
        /// - `view_pubkey`: New public key for scanning payments.
        ///
        /// ## Errors
        /// - `NotRegistered`: No meta-address exists for this account.
        /// - `InvalidPublicKey`: One or both keys are invalid.
        #[pallet::call_index(1)]
        #[pallet::weight(T::WeightInfo::update_meta_address())]
        pub fn update_meta_address(
            origin: OriginFor<T>,
            spend_pubkey: [u8; 32],
            view_pubkey: [u8; 32],
        ) -> DispatchResult {
            let who = ensure_signed(origin)?;

            // Check already registered
            ensure!(
                StealthMetaAddresses::<T>::contains_key(&who),
                Error::<T>::NotRegistered
            );

            // Validate keys
            ensure!(spend_pubkey != [0u8; 32], Error::<T>::InvalidPublicKey);
            ensure!(view_pubkey != [0u8; 32], Error::<T>::InvalidPublicKey);
            ensure!(spend_pubkey != view_pubkey, Error::<T>::IdenticalKeys);

            // Update the meta-address
            let meta_address = StealthMetaAddress {
                spend_pubkey,
                view_pubkey,
            };
            StealthMetaAddresses::<T>::insert(&who, meta_address);

            Self::deposit_event(Event::MetaAddressUpdated {
                account: who,
                spend_pubkey,
                view_pubkey,
            });

            Ok(())
        }

        /// Announce a stealth payment by publishing the ephemeral public key.
        ///
        /// Recipients scan these announcements to find payments addressed to them.
        ///
        /// ## Arguments
        /// - `origin`: The transaction origin (must be signed).
        /// - `ephemeral_pubkey`: The ephemeral public key R = r*G.
        /// - `encrypted_memo`: Optional encrypted memo for the recipient.
        ///
        /// ## Errors
        /// - `TooManyEphemeralKeys`: Block limit for ephemeral keys reached.
        /// - `InvalidPublicKey`: Ephemeral key is invalid.
        /// - `MemoTooLarge`: Memo exceeds maximum size.
        #[pallet::call_index(2)]
        #[pallet::weight(T::WeightInfo::announce_payment())]
        pub fn announce_payment(
            origin: OriginFor<T>,
            ephemeral_pubkey: [u8; 32],
            encrypted_memo: Option<Vec<u8>>,
        ) -> DispatchResult {
            ensure_signed(origin)?;

            // Validate ephemeral key
            ensure!(ephemeral_pubkey != [0u8; 32], Error::<T>::InvalidPublicKey);

            // Process memo
            let memo: BoundedVec<u8, T::MaxMemoSize> = match encrypted_memo {
                Some(m) => m.try_into().map_err(|_| Error::<T>::MemoTooLarge)?,
                None => BoundedVec::default(),
            };

            let block = frame_system::Pallet::<T>::block_number();
            let has_memo = !memo.is_empty();

            // Create announcement
            let announcement = EphemeralKeyAnnouncement {
                ephemeral_pubkey,
                block_number: block,
                encrypted_memo: memo,
            };

            // Add to storage
            EphemeralKeys::<T>::try_mutate(block, |keys| {
                keys.try_push(announcement).map_err(|_| Error::<T>::TooManyEphemeralKeys)
            })?;

            // Update metrics
            TotalEphemeralKeys::<T>::mutate(|count| *count = count.saturating_add(1));

            Self::deposit_event(Event::StealthPaymentAnnounced {
                ephemeral_pubkey,
                block,
                has_memo,
            });

            Ok(())
        }
    }

    /// Internal helper functions.
    impl<T: Config> Pallet<T> {
        /// Get a meta-address for an account.
        pub fn get_meta_address(account: &T::AccountId) -> Option<StealthMetaAddress> {
            StealthMetaAddresses::<T>::get(account)
        }

        /// Get all ephemeral keys for a block.
        pub fn get_ephemeral_keys_for_block(
            block: BlockNumberFor<T>
        ) -> Vec<EphemeralKeyAnnouncement<T>> {
            EphemeralKeys::<T>::get(block).into_inner()
        }

        /// Get ephemeral keys in a range of blocks (for scanning).
        pub fn scan_ephemeral_keys(
            from_block: BlockNumberFor<T>,
            to_block: BlockNumberFor<T>,
        ) -> Vec<EphemeralKeyAnnouncement<T>> {
            let mut result = Vec::new();
            let mut current = from_block;
            while current <= to_block {
                result.extend(Self::get_ephemeral_keys_for_block(current));
                current = current.saturating_add(1u32.into());
            }
            result
        }
    }
}
