//! Autogenerated weights for `pallet_stealth_addresses`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0
//! DATE: 2025-08-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chameleon-dev`, CPU: `AMD EPYC 7R32`
//!
//! NOTE: These are placeholder weights. Run benchmarks for production values.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_stealth_addresses.
pub trait WeightInfo {
    fn register_meta_address() -> Weight;
    fn update_meta_address() -> Weight;
    fn announce_payment() -> Weight;
}

/// Weights for pallet_stealth_addresses using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: StealthAddresses StealthMetaAddresses (r:1 w:1)
    /// Storage: StealthAddresses TotalMetaAddresses (r:1 w:1)
    fn register_meta_address() -> Weight {
        Weight::from_parts(50_000_000, 3493)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: StealthAddresses StealthMetaAddresses (r:1 w:1)
    fn update_meta_address() -> Weight {
        Weight::from_parts(45_000_000, 3493)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: StealthAddresses EphemeralKeys (r:1 w:1)
    /// Storage: StealthAddresses TotalEphemeralKeys (r:1 w:1)
    fn announce_payment() -> Weight {
        Weight::from_parts(55_000_000, 4000)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

// For use in tests/mocks
impl WeightInfo for () {
    fn register_meta_address() -> Weight {
        Weight::from_parts(50_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn update_meta_address() -> Weight {
        Weight::from_parts(45_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn announce_payment() -> Weight {
        Weight::from_parts(55_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}
