//! Autogenerated weights for `pallet_confidential_transfer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0
//! DATE: 2025-08-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `chameleon-dev`, CPU: `AMD EPYC 7R32`
//!
//! NOTE: These are placeholder weights. Run benchmarks for production values.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_confidential_transfer.
pub trait WeightInfo {
    fn shield() -> Weight;
    fn confidential_transfer() -> Weight;
    fn unshield() -> Weight;
}

/// Weights for pallet_confidential_transfer using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: System Account (r:1 w:1)
    /// Storage: ConfidentialTransfer ShieldedNotes (r:0 w:1)
    /// Storage: ConfidentialTransfer TotalShieldedSupply (r:1 w:1)
    /// Storage: ConfidentialTransfer TotalShieldOperations (r:1 w:1)
    fn shield() -> Weight {
        Weight::from_parts(100_000_000, 5000)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: RingSignatures UsedKeyImages (r:1 w:1)
    /// Storage: ConfidentialTransfer ShieldedNotes (r:1 w:2)
    /// Storage: ConfidentialTransfer TotalConfidentialTransfers (r:1 w:1)
    fn confidential_transfer() -> Weight {
        Weight::from_parts(200_000_000, 6000)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }

    /// Storage: RingSignatures UsedKeyImages (r:1 w:1)
    /// Storage: ConfidentialTransfer ShieldedNotes (r:1 w:1)
    /// Storage: System Account (r:1 w:1)
    /// Storage: ConfidentialTransfer TotalShieldedSupply (r:1 w:1)
    /// Storage: ConfidentialTransfer TotalUnshieldOperations (r:1 w:1)
    fn unshield() -> Weight {
        Weight::from_parts(150_000_000, 6000)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
}

// For use in tests/mocks
impl WeightInfo for () {
    fn shield() -> Weight {
        Weight::from_parts(100_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }

    fn confidential_transfer() -> Weight {
        Weight::from_parts(200_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }

    fn unshield() -> Weight {
        Weight::from_parts(150_000_000, 0)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
}
